name: NodeJS with Webpack

on:
  push:
    branches: [ publish ]
  pull_request:
    branches: [ publish ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Build
        run: |
          npm install
          npx webpack
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: './lib/package.json'
          token: ${{ secrets.NPM_TOKEN }}
